### PR TITLE
fix: accept past-round QBFT decided messages

### LINKED ISSUE #979: QBFT: late-decided absorption blocked by past-round check, contributed to mainnet missed proposal
## Summary

On 2026-04-16, a mainnet validator (idx 4596, slot 14125967) on a 4-operator SSV cluster missed its block proposal because Anchor did not absorb the cluster's own aggregated decided message — it arrived 174 ms after the local round-1 timer fired. The `received_decided` handler exists and would have completed the instance, but the message is rejected upstream by `validate_message` with `QbftError::PastRound` before reaching it. Go-SSV (spec + production) handles decided messages out-of-instance at the controller level and would have absorbed it.

## Incident

- 4-op cluster, 2 operators in one region (op 2042 + op 2044, Anchor) and 2 in another region (op 2045 Anchor + op 2046 Go-SSV). ~150 ms cross-region RTT.
- Round-1 leader: op 2046. Slot start: `2026-04-16 10:33:47.000 UTC`.
- The leader-co-located region reached round-1 COMMIT consensus at **+1.961 s**, signers `[2044, 2045, 2046]`.
- The far-region ops had their round-1 timer fire at **+2.001 s** with only their own COMMIT received locally; peer COMMITs arrived 6–10 ms past the deadline. `end_round()` bumped `current_round` to 2.
- Cluster's aggregated decided message (`operator_ids=[2044, 2045, 2046]`, `qbft_message_type=Commit`, `round=1`) arrived on op 2042 at **+2.175 s** — 174 ms after the timer. Rejected.
- Op 2042 and op 2044 ratcheted through round-changes for the remaining ~10 s. Slot missed.

Sample log lines from one of the affected operators (validator pubkey redacted; full Anchor unit logs available, can share on request):

```
2026-04-16T10:33:48.910909Z DEBUG Reached a PREPARE consensus. State updated to COMMIT  instance_id=… InstanceHeight(14125967)
2026-04-16T10:33:48.912965Z DEBUG COMMIT received  from=OperatorId(2042)  state=Commit{…}   ← only own COMMIT before timer
2026-04-16T10:33:49.001745Z  WARN Round timer elapsed instance_id=… duty=Proposal, InstanceHeight(14125967)
2026-04-16T10:33:49.006918Z DEBUG (COMMIT from 2045 arrives 6ms late, rejected by validate_message)
2026-04-16T10:33:49.007057Z DEBUG (COMMIT from 2044 arrives 6ms late, rejected)
2026-04-16T10:33:49.010901Z DEBUG (COMMIT from 2046 arrives 10ms late, rejected)
2026-04-16T10:33:49.175214Z DEBUG Received message in qbft_instance  msg=…operator_ids=[2044, 2045, 2046], qbft_message_type=Commit, height=14125967, round=1…    ← aggregated decided rejected
2026-04-16T10:33:51.001576Z  WARN Round timer elapsed                                                           ← round 2 expires
… 5 more round-timer firings every 2s …
```

Corroborating metric: `anchor_consensus_times_seconds{type=\"block\"}` p99 over the event hour = **10 s on the two affected ops**, **0.5 s on the third Anchor op**. Peer counts steady, zero handshake failures, BN/EL healthy — confirms this is purely QBFT-internal, not a network or external-dependency issue.

## How Go-SSV handles this

Decided messages are routed at the **Controller** level, before any round/instance check:

- spec: [`ssv-spec/qbft/controller.go#L79-L85`](https://github.com/ssvlabs/ssv-spec/blob/3e47960/qbft/controller.go#L79-L85) — `IsDecidedMsg` short-circuits to `UponDecided` ahead of `UponExistingInstanceMsg`.
- spec: [`ssv-spec/qbft/decided.go#L11-L62`](https://github.com/ssvlabs/ssv-spec/blob/3e47960/qbft/decided.go#L11-L62) — `UponDecided` accepts regardless of current round and rewinds: `inst.State.Round = msg.QBFTMessage.Round`.
- production: [`ssv/protocol/v2/qbft/controller/controller.go#L125-L127`](https://github.com/ssvlabs/ssv/blob/dfff304/protocol/v2/qbft/controller/controller.go#L125-L127), [`ssv/protocol/v2/qbft/controller/decided.go#L14-L65`](https://github.com/ssvlabs/ssv/blob/dfff304/protocol/v2/qbft/controller/decided.go#L14-L65).

Had the affected operators been running Go-SSV, the +2.175 s decided message would have flowed through `Controller.ProcessMsg → UponDecided`, marked the instance decided on round 1, and the slot would not have been missed.

## Why Anchor rejected it

Anchor's late-decided absorber exists and works correctly when reached:

- [`anchor/common/qbft/src/lib.rs#L1166-L1204`](https://github.com/sigp/anchor/blob/4ec67f9/anchor/common/qbft/src/lib.rs#L1166-L1204) — `received_decided` sets `InstanceState::Complete` regardless of QBFT state.
- [`anchor/common/qbft/src/lib.rs#L537-L543`](https://github.com/sigp/anchor/blob/4ec67f9/anchor/common/qbft/src/lib.rs#L537-L543) — multi-signer Commits are dispatched to `received_decided`.

But it's gated behind `validate_message`, which rejects past-round messages with no carve-out for decided ones:

- [`anchor/common/qbft/src/lib.rs#L323-L336`](https://github.com/sigp/anchor/blob/4ec67f9/anchor/common/qbft/src/lib.rs#L323-L336) — past-round → `QbftError::PastRound`, applied to all message types including aggregated commits.
- [`anchor/common/qbft/src/lib.rs#L338-L354`](https://github.com/sigp/anchor/blob/4ec67f9/anchor/common/qbft/src/lib.rs#L338-L354) — symmetric future-round check (added in #534) *does* carve out multi-signer commits: \"Only decided messages (with quorum) are allowed from future rounds\". The past-round path was never given the same treatment.

Net effect: future-round decided messages are accepted; past-round decided messages are not. Once `end_round()` bumps the round, any in-flight decided message from the round that just ended is too old to count.

## Potential fixes

1. **Carve out past-round decided messages, mirroring the future-round case.** In `validate_message`, allow `QbftMessageType::Commit` with `has_quorum(...)` to bypass the `round < current_round` early-return and fall through to the existing `received_decided` dispatch. Smallest change, addresses the reproduced case directly.
2. **Move decided-message routing out of `Qbft::receive` into a controller-level entry point** — matching SSV's Controller vs Instance separation. Bigger refactor; better long-term spec alignment.
3. **Add a regression test:** instance advanced to round N+1, then a decided message for round N arrives → instance must complete. No such test currently exists in `anchor/common/qbft/src/tests.rs`.

Linking #534 (future-round validation) for context — same shape, opposite direction.

### PR DESCRIPTION
**Pull request by diegomrsantos**
## Problem, Evidence, and Context (Required)

- Fixes #979.
- A mainnet proposer duty missed because an Anchor node advanced from round 1 to round 2, then rejected the cluster's quorum-backed round-1 decided message as `PastRound`.
- Anchor already has `received_decided`, and future-round decided commits already bypass the normal round check. The missing part was the same allowance for decided commits from earlier rounds.

## Change Overview (Required)

- Add a narrow past-round carve-out for decided messages, defined locally as `Commit` messages with committee quorum.
- Allow past-round decided messages through `validate_message` instead of returning `PastRound`.
- Leave the existing future-round `Commit` branch behavior unchanged: it still requires quorum.
- Keep the rest of validation unchanged: height, committee membership, full-data decoding, and data validation still run before the instance completes.
- Add a regression test that advances a QBFT instance to round 2, then delivers a quorum-signed round-1 decided commit and verifies the instance completes.

## Risks, Trade-offs, and Mitigations (Required)

- The behavior change is limited to quorum-backed `Commit` messages. Single-signer commits and non-commit messages from past rounds are still rejected.
- The main risk is accepting more messages after local round advancement. The helper keeps the acceptance rule narrow and still relies on the existing signer quorum and committee checks.

## Validation (Required)

- Confirmed the new regression test fails before the fix with `PastRound`.
- Confirmed the new regression test passes after the fix.
- Ran the full `qbft` crate test suite.
- Ran clippy for `qbft` tests.
- The commit hook also ran formatting, full workspace clippy, and Cargo.toml sort checks successfully.
- Checked the diff for whitespace errors.

## Rollback (Required for behavior or runtime changes; optional otherwise)

- Revert this PR. That restores the previous behavior where past-round decided commits are rejected by `validate_message`.
- No config, database, or operational migration is involved.

## Blockers / Dependencies (Optional)

N/A

## Additional Info / Next Steps (Optional)

N/A

### CODE REVIEW

**Comment by diegomrsantos** [comment]
@claude review this PR

File: anchor/common/qbft/src/tests.rs [hunk 1]
```diff
@@ -231,6 +231,93 @@ fn test_node_recovery() {
...
+    );
+    assert!(
+        matches!(
+            &qbft_instance.completed,
+            Some(Completed::Success(root)) if *root == decided_root
+        ),
+        "instance should complete with the decided root, got {:?}",
+        qbft_instance.completed
+    );
+    assert!(qbft_instance.aggregated_commit.is_some());
```
Comment (shane-moore) [inline anchor/common/qbft/src/tests.rs:318]: nit: `received_decided` ( mutates state + data too — adding `assert!(matches!(state, ::Complete))` and `assert!(data.contains_key(&decided_root))` covers the full post-condition. Non-blocking.

```suggestion
    assert!(qbft_instance.aggregated_commit.is_some());
    assert!(matches!(qbft_instance.state, InstanceState::Complete));
    assert!(qbft_instance.data.contains_key(&decided_root));

Comment (diegomrsantos) [reply anchor/common/qbft/src/tests.rs:318]: Done, thanks!

**Review by shane-moore — APPROVED** [review]
LGTM!
